spring:
  datasource:
    url: jdbc:h2:mem:example
    driver-class-name: org.h2.Driver
    username: daniel
    password: daniel
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create